import img1 from "../photos/img1.jpg";
import img2 from "../photos/img2.jpg";
import img3 from "../photos/img3.jpg";
import img4 from "../photos/img4.jpg";
import img5 from "../photos/img5.jpg";
import img6 from "../photos/img6.jpg";
import img7 from "../photos/img7.jpg";
import img8 from "../photos/img8.jpg";
import img9 from "../photos/img9.jpg";
import img10 from "../photos/img10.jpg";
import img11 from "../photos/img11.jpg";
import img12 from "../photos/img12.jpg";
import img13 from "../photos/img13.jpg";
import img14 from "../photos/img14.jpg";
import img15 from "../photos/img15.jpg";
import img16 from "../photos/img16.jpg";
import img17 from "../photos/img17.jpg";
import img18 from "../photos/img18.jpg";
import img19 from "../photos/img19.jpg";
import img20 from "../photos/img20.jpg";
import img21 from "../photos/img21.jpg";
import img22 from "../photos/img22.jpg";
import img23 from "../photos/img23.jpg";
import img24 from "../photos/img24.jpg";

export const ImageData = [
    { img: img1 }, 
    { img: img2 }, 
    { img: img3 }, 
    { img: img4 }, 
    { img: img5 }, 
    { img: img6 }, 
    { img: img7 }, 
    { img: img8 }, 
    { img: img9 }, 
    { img: img10 }, 
    { img: img11 }, 
    { img: img12 },
    { img: img13 }, 
    { img: img14 }, 
    { img: img15 }, 
    { img: img16 }, 
    { img: img17 }, 
    { img: img18 }, 
    { img: img19 }, 
    { img: img20 }, 
    { img: img21 }, 
    { img: img22 }, 
    { img: img23 }, 
    { img: img24 }
];
